# 服务器配置
[server]
port = ":8080"

# mysql配置项
[mysql]
ip = "47.108.59.83"
port = "3306"
database = "douyin"
username = "root"
password = "qxy20220511/*-"
max_idle_conns = 50
Max_open_conns = 100

# redis配置
[redis]
dial = "tcp"
ip = "47.108.59.83"
port = "6379"
password = "qxy20220511/*-"
pool_size = 1000
database = 1
max-idle = 1
max-active = 10

# [logger]
# file_path = './logs/'
# file_name = 'system.log'
# max_size = 10
# max_age = 10
# max_backups = 1
