# 服务器配置
[server]
port = ":8080"

# mysql配置项
[mysql]
# ip = "127.0.0.1"
# database = "douyin"
# password = ""
ip = "47.108.59.83"
database = "dou_yin"
password = "qxy20220511/*-"
port = "3306"
username = "root"

# ip = "8.134.34.95"
# password = "root"
# database = "douyin"
# port = "3306"
# username = "root"

max_idle_conns = 50
Max_open_conns = 100

# redis配置
[redis]
dial = "tcp"
# ip = "192.168.137.103"
# password = "123123"

ip = "47.108.59.83"
password = "qxy20220511/*-"
# ip = "8.134.34.95"
# password = "root"
port = "6379"

pool_size = 1000
database = 1
max-idle = 1
max-active = 10

# [rabbitmq]
url = "amqp://admin123:qxy20220511/*-@47.108.59.83/douyin"
queue ="douyin_queue"


# [logger]
# file_path = './logs/'
# file_name = 'system.log'
# max_size = 10
# max_age = 10
# max_backups = 1